### PR TITLE
Refactor the "Profile file" command to use the same task API

### PR DESCRIPTION
**Pull request by tonybaloney**
- [x] Refactor
- [x] Change to pipe from output files

### CODE REVIEW

**Comment by tonybaloney** [comment]
This is what I currently get though..

```
austin -i 100 --pipe C:\Users\anthonyshaw\AppData\Local\Microsoft\WindowsApps\python3.9.exe c:\Users\anthonyshaw\source\repos\austin-testing\main.py

🔢 Cannot determine the version of the Python interpreter. This could be due
to the binary not being an actual Python binary, like uWSGI. Please report an
issue at

    🌐 https://github.com/P403n1x87/austin/issues

together with details about the application that you were trying to profile,
like frameworks used, command line etc ....
```

**Comment by tonybaloney** [comment]
> > This is what I currently get though..
> 
> 
> 
> Is this because of the `--pipe` option? Does
> 
> ~~~
> 
> C:\Users\anthonyshaw\AppData\Local\Microsoft\WindowsApps\python3.9.exe -V
> 
> ~~~
> 
> print the Python version?

I get that error when I run the command locally as well. Python -V works fine.

**Comment by P403n1x87** [comment]
We would have to look at the logs generated by Austin compiled with `-DDEBUG` and see if this is caused by something else other than it failing to parse the output of https://github.com/P403n1x87/austin/blob/3e8b25fd0a1dedec812979f00b18235851b18892/src/py_proc.c#L147. Perhaps that particular installation of Python (looks like it's coming from an App Store?) doesn't come with symbol names?

**Comment by P403n1x87** [comment]
I think I've found the problem. I've installed Python 3.9 from the Store and reproduced the issue. The binary in the user area is a launcher for the actual Python binary, which in my case is at
~~~
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\python3.9.exe
~~~
The way Austin executes this binary on Windows doesn't handle the space in the path and so it gets
~~~
'C:\Program' is not recognized as an internal or external command, operable program or batch file.
~~~
instead of the expected Python version 😞 . The process is spawned with `_popen`: https://github.com/P403n1x87/austin/blob/3e8b25fd0a1dedec812979f00b18235851b18892/src/py_proc.c#L149, so I guess Austin needs a more robust way of executing a binary.

**Comment by P403n1x87** [comment]
Should be fixed by https://github.com/P403n1x87/austin/commit/a11baa4006f19fdf7da9ffec495beea94a053207

**Comment by P403n1x87** [comment]
@tonybaloney what's the status of this PR? It would be great to have this feature in and released! 🙂

**Comment by tonybaloney** [comment]
Looks like I need to rebase but it's done

**Comment by tonybaloney** [comment]
@P403n1x87 should be good to go 👍🏻

**Comment by P403n1x87** [comment]
@tonybaloney awesome, thanks! Will soon make a new release!

**Pull request merged**
